Fix key bindings in vi mode and add compatibility for Fisher 4.2.0+
oh-my-fish/plugin-bang-bang pull request #8
Opened 2021-02-14 11:07 UTC by akuntsch

Fixes #4, #7.

I also added a Fisher uninstall function which erases the key bindings on removal via Fisher.

2021-02-27 11:56 UTC, nzig commented
This would also fix issues with Fisher: https://github.com/jorgebucaran/fisher/issues/651

2021-02-27 15:37 UTC, scorphus requested changes
Thanks for contributing! This is not yet fullt supported by OMF, but as there's no `uninstall` hook, I guess there won't be real difference for current users.

Please mind my change request.

2021-02-27 15:37 UTC, scorphus commented on conf.d/plugin-bang-bang.fish
> +
How about removing this line? Implementation details are implementation details :-)
```suggestion
```

2021-02-27 17:06 UTC, akuntsch commented
I've removed the `echo` and added an `uninstall` hook for OMF which removes the keybindings.

2021-03-02 23:10 UTC, scorphus approved these changes

2021-03-02 23:13 UTC, merged

2021-03-02 23:13 UTC, scorphus commented
Thanks @akuntsch !